Feat/timing game
kanata0510/CreativeAI2024 pull request #26
Opened 2024-06-28 17:09 UTC by 5884-u

タイミングゲーです。

TimingGameMain : タイミングゲーの判定や繰り返しテキストウィンドウへの遷移(仕様書より)を行うクラス
TimingSlider : タイミングゲーのやくものを制御するクラス

2024-06-28 17:37 UTC, kanata0510 requested changes
あと少し直してね

2024-06-28 17:37 UTC, kanata0510 commented on Assets/Scripts/TimingGame/TimingSlider.cs
> +    [SerializeField, HeaderAttribute("範囲:0-1")] private float ascendSpeed;
```suggestion
    [SerializeField, Range(0f, 1f)] private float ascendSpeed;
```

2024-06-28 17:37 UTC, kanata0510 commented on Assets/Scripts/TimingGame/TimingSlider.cs
> +    public void InitializeSliderParameter()  //スライダーが停止された後繰り返すため
もっと使う側を意識した名前にしてほしい。技術駆動命名はInitialize()以外禁止！

2024-06-28 17:37 UTC, kanata0510 commented on Assets/Scripts/TimingGame/TimingSlider.cs
判定位置がRectTransformの最大値に固定されているから、移動できるといいかも

2024-06-28 17:37 UTC, kanata0510 commented on Assets/Scripts/TimingGame/TimingGameMain.cs
> +        else judgeText.text += "<color=#0000FF>Bad</color>";
最後にjudgeText.textに代入する形になるとより良い

2024-06-28 17:37 UTC, kanata0510 commented on Assets/Scripts/TimingGame/TimingGameMain.cs
仕様書によると失敗回数を記録できるといいかも

2024-06-28 20:56 UTC, 5884-u commented on Assets/Scripts/TimingGame/TimingSlider.cs
現状でもsliderの上限・下限を超えない範囲で自由に置けるはず
justTimingは判定時間に変化していて、justTimingに含まれるsliderRectTransform.rect.heightは比例定数
justTiming自体は、sliderの下限から見たtimingBarのy座標とsliderの座標ベースでの速度で計算される

2024-06-28 20:56 UTC, 5884-u commented on Assets/Scripts/TimingGame/TimingGameMain.cs
現状の方法は向こうにも確認済み
また、現状の方法のほうがタイミングゲーの反復回数の変化に強く、薬の調合という都合上成績に説得力を持たせやすそう
(失敗回数だとどんなひどい失敗をしても1ミスは1ミスにしかならない)

2024-06-29 12:36 UTC, kanata0510 commented on Assets/Scripts/TimingGame/TimingSlider.cs
> +
```suggestion

[RequireComponent(typeof(Slider))]
```

2024-06-29 12:37 UTC, kanata0510 approved these changes

2024-06-29 12:38 UTC, merged