Feat/UI
kanata0510/CreativeAI2024 pull request #9
Opened 2024-06-13 12:02 UTC by uwatcha

2024-06-14 03:45 UTC, kanata0510 approved these changes
頑張ってね

2024-06-14 05:09 UTC, uwatcha commented
全て修正したので確認お願いします

2024-06-14 05:17 UTC, kanata0510 requested changes
Actionはイベントに関連するキーワードなのでスクリプト名に使わないでほしい。

2024-06-14 05:17 UTC, kanata0510 commented on Assets/Scripts/UI/MoveButtonFocus.cs
もう一度コメントを呼んで書き直してほしい

2024-06-14 05:17 UTC, kanata0510 commented on Assets/Scripts/UI/OpenWindowAction.cs
> +    private void ChangeActive(GameObject gameObject, bool isActive)
gameObjectは名前かぶるから変えてほしい

2024-06-16 14:09 UTC, kanata0510 requested changes
直してください

2024-06-16 14:09 UTC, kanata0510 commented on Assets/Scripts/UI/MoveCursor.cs
> +            focusedButton = focusCandidate;
副作用があるので本当はあまりよくない

2024-06-16 14:09 UTC, kanata0510 commented on Assets/Scripts/UI/OpenAndCloseWindowTree.cs
> +    public void OpenAndClose() //どのウィンドウを開けてるかの状態もリセットしたい。各ウィンドウのdisenable()の中で処理した方がいい？
このコメントは不要なので消してほしい

2024-06-16 14:09 UTC, kanata0510 commented on Assets/Scripts/UI/SetFirstButtonFocus.cs
ファイル名とクラス名が違うので直してね

2024-06-16 14:09 UTC, kanata0510 commented on Assets/Scripts/UI/OpenAndCloseWindowTree.cs
OpenAndCloseってもう少しいい言葉がありそうだから名前変更してほしい

2024-06-16 15:52 UTC, kanata0510 requested changes
あと一か所だけなんとかしてくれ

2024-06-16 15:52 UTC, kanata0510 commented on Assets/Scripts/UI/MoveCursor.cs
> +        Selectable focusCandidate = focusedButton.FindSelectableOnUp() ? focusedButton.FindSelectableOnUp() : focusedButton;
focusedButton.FindSelectableOnUp()はboolを返さないので三項演算子を使うのは不適切

2024-06-16 17:01 UTC, merged